### ISSUE TITLE
New Asset Bugs

### ISSUE THREAD

**Issue by ElsinoreBrewmaster** [stockto2/desktophero_django#24]
1.) New weapons and Items don't appear in the Editor menu. 

2.) I created a new hand, and it works and appears properly placed in the Editor, but when exported to an STL and loaded into Cura the hand is located in the center of the torso.

![elsinoretest](https://user-images.githubusercontent.com/34317751/33680533-eb7f515e-da8f-11e7-8451-23c316a9fa20.jpg)

**Comment by stockto2** [comment]
1) What category did you specify for the weapon/item?

2) Still trying to figure out what's up with this. Export seems to work correctly for flexible meshes but not for rigid meshes. Could you provide the original file you uploaded?

**Comment by ElsinoreBrewmaster** [comment]
[Character Models.zip](https://github.com/stockto2/desktophero_django/files/1539157/Character.Models.zip)

**Comment by ElsinoreBrewmaster** [comment]
I tried each of these.

Category: weapons, items

Attach to: weapons, weapons (there are two of them, I tried both.)

**Comment by ElsinoreBrewmaster** [comment]
Yesterday, I tried to add a hair asset. Category - hair Attached to - head. It also does not appear in the Editor after submission. I did log out, clear my browser history, then log back in. So, I don't think it's a local issue.

**Comment by stockto2** [comment]
Hey there Brewmaster, I believe all these bugs are fixed now. Try again and let me know what happens.

**Comment by ElsinoreBrewmaster** [comment]
There's still a problem with the export to stl. Here's the pic and files.

[Test1.zip](https://github.com/stockto2/desktophero_django/files/1546783/Test1.zip)
![test](https://user-images.githubusercontent.com/34317751/33818822-16a41fbc-de15-11e7-9eec-8ce0ef920eb0.jpg)

**Comment by ElsinoreBrewmaster** [comment]
Success! Good work! I'll keep creating assets and testing things out.
